#cloud-config
package_update: true

runcmd:
  - |
    # Find the interface that has our private IP
    PRIV_IFACE=$(ip -o addr show | grep '${agent_private_ip}' | awk '{print $2}')
    curl -sfL https://get.k3s.io | K3S_URL=https://${server_private_ip}:6443 K3S_TOKEN=${k3s_token} sh -s - agent \
      --node-ip ${agent_private_ip} \
      --flannel-iface "$PRIV_IFACE"
