"""transcript_entry_status_enum

Revision ID: 5db499581461
Revises: b7c2e4f1a8d3
Create Date: 2026-04-12 18:46:15.116442

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5db499581461"
down_revision: Union[str, None] = "b7c2e4f1a8d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    transcriptentrystatus = sa.Enum(
        "waiting_to_be_processed", "processed", name="transcriptentrystatus"
    )
    transcriptentrystatus.create(op.get_bind())
    op.alter_column(
        "session_transcript_entries",
        "status",
        existing_type=sa.TEXT(),
        type_=transcriptentrystatus,
        existing_nullable=False,
        postgresql_using="status::transcriptentrystatus",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "session_transcript_entries",
        "status",
        existing_type=sa.Enum(
            "waiting_to_be_processed", "processed", name="transcriptentrystatus"
        ),
        type_=sa.TEXT(),
        existing_nullable=False,
        postgresql_using="status::text",
    )
    sa.Enum(name="transcriptentrystatus").drop(op.get_bind())
    # ### end Alembic commands ###
