apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: monorepo
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: ghcr.io/danielpassy/monorepo-web:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: monorepo
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 8000
